name: JSON_VALIDATION
on:
    pull_request:
     branches:
       - "*"
     types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: anyone-developer/anyone-validate-json@main
            with:
              file-extension: '.json'
              ignore-files: 'README.md'
              ignore-directories: '.git'
              read-path: 'contribution'
